;;; biome-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from biome.el

(register-definition-prefixes "biome" '("biome"))


;;; Generated autoloads from biome-api.el

(register-definition-prefixes "biome-api" '("biome-"))


;;; Generated autoloads from biome-api-data.el

(register-definition-prefixes "biome-api-data" '("biome-api-"))


;;; Generated autoloads from biome-api-parse.el

(register-definition-prefixes "biome-api-parse" '("biome-api-parse--"))


;;; Generated autoloads from biome-grid.el

(register-definition-prefixes "biome-grid" '("biome-grid"))


;;; Generated autoloads from biome-multi.el

(register-definition-prefixes "biome-multi" '("biome-multi-"))


;;; Generated autoloads from biome-query.el

(register-definition-prefixes "biome-query" '("biome-"))

;;; End of scraped data

(provide 'biome-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; biome-autoloads.el ends here
